export const BACKGROUND_ACTIONS = {
  GET_BOOKMARKS: "GET_BOOKMARKS",
  GET_HISTORY: "GET_HISTORY",
  GET_SEARCH_SUGGESTIONS: "GET_SEARCH_SUGGESTIONS",
  SEARCH_QUERY: "SEARCH_QUERY",
}

export type BackgroundAction = keyof typeof BACKGROUND_ACTIONS
