export const BACKGROUND_ACTIONS = {
  GET_BOOKMARKS: "GET_BOOKMARKS",
  GET_HISTORY: "GET_HISTORY",
  SEARCH_QUERY: "SEARCH_QUERY",
}

export type BackgroundAction = keyof typeof BACKGROUND_ACTIONS

export const ALARMS = {
  FETCH_ONLINE_IMAGES: "FETCH_ONLINE_IMAGES",
}
