export const BACKGROUND_ACTIONS = {
	ENSURE_ROOT_BOOKMARK_FOLDER: "ENSURE_ROOT_BOOKMARK_FOLDER",
	SEARCH_QUERY: "SEARCH_QUERY",
};

export const ALARMS = {
	FETCH_ONLINE_IMAGES: "FETCH_ONLINE_IMAGES",
};
